import { FORM_10_8678 } from './constants';

const { VHA_MEDICAL_FACILITY } = FORM_10_8678;

export const VA_MEDICAL_FACILITIES_LIST = [
  { stationId: '358', label: 'Manila, Philippines' },
  { stationId: '402', label: 'Togus ME' },
  { stationId: '405', label: 'White River Junction VT' },
  { stationId: '436', label: 'Montana HCS (Fort Harrison MT)' },
  { stationId: '437', label: 'Fargo, ND (CACHE 5.0)' },
  { stationId: '438', label: 'Sioux Falls SD (CACHE 5.0)' },
  { stationId: '442', label: 'Cheyenne WY' },
  { stationId: '452', label: 'Wichita (inactivated 10/1/2001)' },
  { stationId: '459', label: 'VA Pacific Islands HCS (Honolulu HI)' },
  { stationId: '460', label: 'Wilmington DE' },
  { stationId: '463', label: 'Alaska VAHSRO (Anchorage AK)' },
  { stationId: '500', label: 'Albany (inactivated 7/1/2000)' },
  { stationId: '501', label: 'New Mexico HCS (Albuquerque NM)' },
  { stationId: '502', label: 'Alexandria, LA' },
  { stationId: '503', label: 'Altoona, PA' },
  { stationId: '504', label: 'Amarillo HCS (Amarillo TX)' },
  { stationId: '506', label: 'Ann Arbor, MI' },
  { stationId: '508', label: 'Atlanta, GA' },
  { stationId: '509', label: 'Augusta, GA' },
  { stationId: '512', label: 'Maryland HCS (Baltimore MD)' },
  { stationId: '514', label: 'Bath (inactivated 7/1/2000)' },
  { stationId: '515', label: 'Battle Creek, MI' },
  { stationId: '516', label: 'Bay Pines,FL' },
  { stationId: '517', label: 'Beckley, WV' },
  { stationId: '518', label: 'Bedford,MA' },
  { stationId: '519', label: 'West Texas HCS (Big Spring TX)' },
  { stationId: '520', label: 'Biloxi, MS' },
  { stationId: '521', label: 'Birmingham, AL' },
  { stationId: '523', label: 'Boston HCS (Boston)' },
  { stationId: '526', label: 'Bronx, NY' },
  { stationId: '528', label: 'Upstate New York HCS' },
  { stationId: '529', label: 'Butler, PA' },
  { stationId: '531', label: 'Boise,ID' },
  { stationId: '532', label: 'Canandaigua, NY (inactivated 10/1/1999)' },
  { stationId: '534', label: 'Charleston, SC' },
  { stationId: '537', label: 'Chicago (Westside), IL' },
  { stationId: '538', label: 'Chillicothe, OH' },
  { stationId: '539', label: 'Cincinnati, OH' },
  { stationId: '540', label: 'Clarksburg, WV' },
  { stationId: '541', label: 'Cleveland, OH' },
  { stationId: '542', label: 'Coatesville, PA' },
  { stationId: '543', label: 'Columbia, Missouri (inactivated 4/1/2001)' },
  { stationId: '544', label: 'Columbia, SC' },
  { stationId: '546', label: 'Miami, FL' },
  { stationId: '548', label: 'West Palm Beach, FL' },
  { stationId: '549', label: 'North Texas HCS (Dallas TX)' },
  { stationId: '550', label: 'Illiana HCS (Danville IL)' },
  { stationId: '552', label: 'Dayton, OH' },
  { stationId: '553', label: 'Detroit, MI' },
  { stationId: '554', label: 'Eastern Colorado HCS (Denver CO)' },
  { stationId: '555', label: 'Des Moines (inactivated 7/1/2000)' },
  { stationId: '556', label: 'North Chicago, IL' },
  { stationId: '557', label: 'Dublin, GA' },
  { stationId: '558', label: 'Durham, NC' },
  { stationId: '561', label: 'New Jersey HCS (East Orange)' },
  { stationId: '562', label: 'Erie, PA' },
  { stationId: '564', label: 'Fayetteville, AR' },
  { stationId: '565', label: 'Fayetteville, NC' },
  { stationId: '567', label: 'Ft. Lyon, Colo (inactivated 10/1/2001)' },
  { stationId: '568', label: 'Black Hills HCS (Fort Meade SD) (CACHE 5.0)' },
  { stationId: '570', label: 'Central California HCS (Fresno CA)' },
  { stationId: '573', label: 'N. Florida/S. Georgia HCS (Gainesville FL)' },
  { stationId: '575', label: 'Grand Junction, CO' },
  { stationId: '578', label: 'Hines, IL' },
  { stationId: '580', label: 'Houston, TX' },
  { stationId: '581', label: 'Huntington, WV' },
  { stationId: '583', label: 'Indianapolis, IN' },
  { stationId: '584', label: 'Iowa City, IA' },
  { stationId: '585', label: 'Iron Mountain, MI' },
  { stationId: '586', label: 'Jackson, MS' },
  { stationId: '589', label: 'VA Heartland West (Kansas City MO)' },
  { stationId: '590', label: 'Hampton, VA' },
  { stationId: '593', label: 'Southern Nevada HCS (Las Vegas NV)' },
  { stationId: '595', label: 'Lebanon, PA' },
  { stationId: '596', label: 'Lexington, KY' },
  { stationId: '597', label: 'Greater Nebraska' },
  { stationId: '598', label: 'Central Arkansas HCS (Little Rock AR)' },
  { stationId: '600', label: 'Long Beach HCS (Long Beach CA)' },
  { stationId: '603', label: 'Louisville, KY' },
  { stationId: '605', label: 'Loma Linda, CA' },
  { stationId: '607', label: 'Madison, WI' },
  { stationId: '608', label: 'Manchester, NH' },
  { stationId: '609', label: 'Marion, IL' },
  { stationId: '610', label: 'Northern Indiana HCS (Marion, IN)' },
  { stationId: '612', label: 'Northern California HCS (Martinez CA)' },
  { stationId: '613', label: 'Martinsburg, WV' },
  { stationId: '614', label: 'Memphis, TN' },
  { stationId: '618', label: 'Minneapolis, MN (CACHE 5.0)' },
  { stationId: '619', label: 'Central Alabama HCS (Montgomery AL)' },
  { stationId: '620', label: 'Hudson Valley HCS (Castle Point, Montrose)' },
  { stationId: '621', label: 'Mountain Home, TN' },
  { stationId: '622', label: 'Murfreesboro, TN' },
  { stationId: '623', label: 'Muskogee, OK' },
  { stationId: '626', label: 'Tennessee Valley HCS (Nashville TN)' },
  { stationId: '629', label: 'New Orleans, LA' },
  { stationId: '630', label: 'New York HHS (Brooklyn)' },
  { stationId: '631', label: 'Northampton, MA' },
  { stationId: '632', label: 'Northport, NY' },
  { stationId: '635', label: 'Oklahoma City, OK' },
  { stationId: '636', label: 'Central Plains HCS (Omaha NE)' },
  { stationId: '637', label: 'Asheville, NC' },
  { stationId: '640', label: 'Palo Alto HCS (Palo Alto CA)' },
  { stationId: '642', label: 'Philadelphia, PA' },
  { stationId: '644', label: 'Phoenix, AZ' },
  { stationId: '646', label: 'Pittsburgh HCS (Pittsburgh PA)' },
  { stationId: '647', label: 'Poplar Bluff, MO' },
  { stationId: '648', label: 'Portland, OR (CACHE 5.0)' },
  { stationId: '649', label: 'Northern Arizona HCS (Prescott AZ)' },
  { stationId: '650', label: 'Providence, RI' },
  { stationId: '652', label: 'Richmond, VA' },
  { stationId: '653', label: 'Roseburg HCS (Roseburg OR)' },
  { stationId: '654', label: 'Sierra Nevada HCS (Reno NV)' },
  { stationId: '655', label: 'Saginaw, MI' },
  { stationId: '656', label: 'St. Cloud, MN (CACHE 5.0)' },
  { stationId: '657', label: 'VA Heartland East (Saint Louis MO)' },
  { stationId: '658', label: 'Salem, VA' },
  { stationId: '659', label: 'Salisbury, NC' },
  { stationId: '660', label: 'Salt Lake City HCS (Salt Lake City UT)' },
  { stationId: '662', label: 'San Francisco, CA' },
  { stationId: '663', label: 'Puget Sound HCS (Seattle WA) (CACHE 5.0)' },
  { stationId: '664', label: 'San Diego HCS (San Diego CA)' },
  { stationId: '666', label: 'Sheridan, WY' },
  { stationId: '667', label: 'Shreveport, LA' },
  { stationId: '668', label: 'Spokane, WA' },
  { stationId: '670', label: 'Syracuse, NY (inactivated 4/1/2000)' },
  { stationId: '671', label: 'South Texas HCS (San Antonio TX)' },
  { stationId: '672', label: 'San Juan, PR' },
  { stationId: '673', label: 'Tampa, FL' },
  { stationId: '674', label: 'Central Texas HCS (Temple TX)' },
  { stationId: '675', label: 'Orlando, FL' },
  { stationId: '676', label: 'Tomah, WI' },
  { stationId: '677', label: 'Topeka, KS' },
  { stationId: '678', label: 'Southern Arizona HCS (Tucson AZ)' },
  { stationId: '679', label: 'Tuscaloosa, AL' },
  { stationId: '687', label: 'Walla Walla, WA' },
  { stationId: '688', label: 'Washington DC' },
  { stationId: '689', label: 'Connecticut HCS (Westhaven)' },
  { stationId: '691', label: 'Greater Los Angeles HCS (Los Angeles CA)' },
  { stationId: '692', label: 'White City, OR (CACHE 5.0)' },
  { stationId: '693', label: 'Wilkes-Barre, PA' },
  { stationId: '695', label: 'Milwaukee, WI' },
  { stationId: '740', label: 'Texas Valley Coastal Bend HCS (Harlingen TX)' },
  { stationId: '756', label: 'El Paso, TX' },
  { stationId: '757', label: 'Columbus, OH' },
];

export const VHA_MEDICAL_FACILITY_OPTIONS = [
  ...VA_MEDICAL_FACILITIES_LIST.map(({ label }) => label),
  VHA_MEDICAL_FACILITY.OTHER_OPTION,
];

export const VHA_MEDICAL_FACILITY_LABELS = VHA_MEDICAL_FACILITY_OPTIONS.reduce(
  (acc, option) => {
    acc[option] = option;
    return acc;
  },
  {},
);
